# Generated by Django 5.2.6 on 2025-10-03 09:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ads', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='favoritead',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_ads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='petad',
            name='animal_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ads', to='ads.animaltype'),
        ),
        migrations.AddField(
            model_name='petad',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='favoritead',
            name='ad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='ads.petad'),
        ),
        migrations.AddField(
            model_name='comment',
            name='ad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='ads.petad'),
        ),
        migrations.AddField(
            model_name='petphoto',
            name='ad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='ads.petad'),
        ),
        migrations.AddIndex(
            model_name='petad',
            index=models.Index(fields=['animal_type', 'is_active'], name='ads_petad_animal__7b8ac9_idx'),
        ),
        migrations.AddIndex(
            model_name='petad',
            index=models.Index(fields=['location'], name='ads_petad_locatio_ef078d_idx'),
        ),
        migrations.AddIndex(
            model_name='petad',
            index=models.Index(fields=['date_lost'], name='ads_petad_date_lo_c628df_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='favoritead',
            unique_together={('user', 'ad')},
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['ad', 'created_at'], name='ads_comment_ad_id_e77913_idx'),
        ),
    ]
