# Generated by Django 5.2.6 on 2025-09-29 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petad',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
