# Generated by Django 5.2.6 on 2025-09-28 14:04

import users.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_email_alter_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=15, unique=True, validators=[users.validators.validate_phone]),
        ),
    ]
